<?php

function workshops_perm() {
	return array('Workshop Organiser Adding','Workshop Add New College', 'Workshop Get College', 'Workshop Admin List', 'Workshop Organiser College', 'Workshop Request', 'Workshop Request List', 'Test Request', 'Test Request List', 'Test Admin List', 'Workshop Detail', 'Feedback', 'ajax request', 'Academic Center', 'Edit Organiser Details', 'Report Public View');
}

function workshops_menu(){

	$items = array();

	$items['workshops/aworkshop_request'] = array(
		'title' => 'Live Workshop Request',
		'description' => 'Workshop Admin List',
		'page callback' => 'aworkshops_workshop_request',
		'access arguments' => array('Workshop Request'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'aworkshop_request.inc',
	);

	$items['workshops/report'] = array(
       'title' => 'Reports',
       'description' => 'report',
       'access arguments' => array('Report Public View'),
       'page arguments' => array('workshop_completed'),
       'file' => 'report.inc'
    );
    $items['workshops/report/cworkshop'] = array(
		'title' => 'Completed Workshop Details',
		'page arguments' => array('workshop_completed'),
		'access arguments' => array('Report Public View'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'report.inc',
	);
	$items['workshops/college'] = array(
		'title' => 'College Details',
       		'description' => 'college details',
       		'page callback' => 'drupal_get_form',
       		'page callback' => 'workshops_list_college_details',
       		'access arguments' => array('Workshop Add New College'),
       		'file' => 'add_college.inc'
    	);
	$items['workshops/add_resource_person'] = array(
		'title' => 'Add New Resource Person',
		'description' => 'Adding new resource preson\'s detail', 
		'page callback' => 'drupal_get_form',
		'page arguments' => array('workshops_add_resource_person_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'add_resource_person.inc',
	);
	$items['workshops/college/add_college'] = array(
		'title' => 'Add New College Details',
		'description' => 'Adding new college details detail',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('workshops_add_college_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/edit_college'] = array(
		'title' => 'Edit College Details',
		'description' => 'Adding new college details detail',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('workshops_edit_college_form'),
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/list_college'] = array(
		'title' => 'Listing College Details',
		'page callback' => 'workshops_list_college_details',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/list_organisers'] = array(
		'title' => 'Listing Organiser Details',
		'page callback' => 'workshops_list_organisers_detail',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/list_pending_organisers'] = array(
		'title' => 'Pending Organiser Requests',
		'page callback' => 'workshops_list_organiser_requests',
		'access arguments' => array('Workshop Add New College'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'add_college.inc',
	);
	$items['workshops/accept_organiser'] = array(
		'title' => 'Accept Organiser Details',
		'page callback' => 'accept_organiser',
		'access arguments' => array('Edit Organiser Details'),
		'page arguments' => array(2),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'organiser.inc',
	);
	$items['workshops/reject_organiser'] = array(
		'title' => 'Reject Organiser Details',
		'page callback' => 'reject_organiser',
		'access arguments' => array('Edit Organiser Details'),
		'page arguments' => array(2),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'organiser.inc',
	);
	$items['workshops/edit_organiser'] = array(
		'title' => 'Edit Organiser Details',
		'page callback' => 'edit_organiser',
		'access arguments' => array('Edit Organiser Details'),
		'page arguments' => array(2),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'add_college.inc',
	);
	$items['workshops/view_organiser'] = array(
		'title' => 'Organiser Details',
		'page callback' => 'view_organiser',
		'access arguments' => array('Edit Organiser Details'),
		'page arguments' => array(2),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/view_college'] = array(
		'title' => 'College Details',
		'page callback' => 'workshops_view_college_details',
		'access arguments' => array('Academic Center'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'add_college.inc',
	);
	$items['workshops/college/get_college_details'] = array(
		'title' => 'Add New College Details',
		'description' => 'Adding new college details detail',
		'page callback' => 'get_college_details',
		'access arguments' => array('Workshop Get College'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['workshops/add_organiser'] = array(
		'title' => 'Add Organiser Details',
		'description' => 'Adding new Organiser details',
		'page callback' => 'workshops_add_organiser',
		'access arguments' => array('Workshop Organiser Adding'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'organiser.inc',
	);
	$items['workshops/get_academic_details'] = array(
		'title' => 'Add New College Details',
		'description' => 'Adding new college details detail',
		'page callback' => 'get_academic_details',
		'access arguments' => array('ajax request'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['workshops/workshop_request'] = array(
		'title' => 'Workshop Request',
		'description' => 'Request for workshops',
		'page callback' => 'workshops_workshop_request',
		'access arguments' => array('Workshop Request'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/list_workshop_request'] = array(
		'title' => 'List Of Pending Workshop Requests',
		'page callback' => 'workshops_list_workshop_request',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/list_workshop_approval'] = array(
		'title' => 'List Of Approved Workshop Requests',
		'page callback' => 'workshops_list_workshop_approval',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/list_workshop_completed'] = array(
		'title' => 'List Of Completed Workshops',
		'page callback' => 'workshops_list_workshop_completed',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/workshop_confirm'] = array(
		'title' => 'Confirm Workshop Request Details',
		'page callback' => 'workshops_workshop_confirm',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/workshop_edit'] = array(
		'title' => 'Edit Workshop Approval Details',
		'page callback' => 'workshops_workshop_edit',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/manage_workshops'] = array(
		'title' => 'List Of Completed Workshops',
		'page callback' => 'workshops_admin_workshop_completed',
		'access arguments' => array('Workshop Admin List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/view_workshop'] = array(
		'title' => 'Workshop Detail',
		'page callback' => 'workshops_view_workshop',
		'access arguments' => array('Workshop Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_request.inc',
	);
	$items['workshops/test_request'] = array(
		'title' => 'Test Request',
		'description' => 'Request for Test',
		'page callback' => 'workshops_test_request',
		'access arguments' => array('Test Request'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/list_test_request'] = array(
		'title' => 'List Of Pending Test Requests',
		'page callback' => 'workshops_list_test_request',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/list_test_approval'] = array(
		'title' => 'List Of Approved Test Requests',
		'page callback' => 'workshops_list_test_approval',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/list_test_completed'] = array(
		'title' => 'List Of Completed Tests',
		'page callback' => 'workshops_list_test_completed',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/manage_tests'] = array(
		'title' => 'List Of Approved Test Requests',
		'page callback' => 'workshops_admin_test_approval',
		'access arguments' => array('Test Admin List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/test_confirm'] = array(
		'title' => 'Confirm Test Request Details',
		'page callback' => 'workshops_test_confirm',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/test_view'] = array(
		'title' => 'Test Approval Details',
		'page callback' => 'workshops_test_view',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/test_edit'] = array(
		'title' => 'Edit Test Approval Details',
		'page callback' => 'workshops_test_edit',
		'access arguments' => array('Test Request List'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_request.inc',
	);
	$items['workshops/test_detail'] = array(
		'title' => 'Test admin details',
		'page callback' => 'test_detail',
		'access arguments' => array('Workshop Detail'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'test_detail.inc'
	);
	$items['workshops/workshop_detail'] = array(
		'title' => 'Workshop details',
		'page callback' => 'workshop_detail',
		'access arguments' => array('Workshop Detail'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'workshop_detail.inc'
	);
	$items['workshops/get_workshop_details'] = array(
		'title' => 'Test admin details',
		'page callback' => 'get_workshop_details',
		'access arguments' => array('Workshop Detail'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['workshops/get_feedback_detail'] = array(
		'title' => 'Add New College Details',
		'description' => 'Get feedback Details',
		'page callback' => 'get_feedback_detail',
		'access arguments' => array('Feedback'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['workshops/feedback/%/%'] = array(
		'title' => 'Feedback',
		'page arguments' => array(2,3),
		'page callback' => 'view_feedback',
		'access arguments' => array('Feedback'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'feedback.inc'
	);
	$items['workshops/get_lang'] = array(
		'title' => 'Workshop Detail',
		'page callback' => 'get_lang',
		'access arguments' => array('ajax request'),
		'type' => MENU_NORMAL_ITEM,
	);
	// email check
	$items['workshops/check_email'] = array(
		'page callback' => 'check_email',
		'access arguments' => array('ajax request'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['workshops/academic_details'] = array(
		'title' => 'Academic Details',
		'page callback' => 'academic_details',
		'access arguments' => array('Academic Center'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'academic_details.inc',
	);
	$items['workshops/get_batches'] = array(
		'title' => 'Get batches list',
		'page callback' => 'get_batches',
		'access arguments' => array('ajax request'),
		'type' => MENU_NORMAL_ITEM,
	);

  return $items;
}

function get_batches(){
	if(isset($_POST['test_code'])){
		$query = "select batches from test_requests where test_code='".$_POST['test_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		if($row = db_fetch_object($result)){
			echo json_encode($row->batches);
			exit;
		}else{
			echo json_encode('0');
			exit;
		}
	}
}

//echec email
function check_email(){
	$query = "select uid, name from users where mail='".$_POST['email']."'";
	$result = db_query($query);
	$row = db_fetch_object($result);
	$data = array();
	if($row){
		$data = $row;
	}
	echo json_encode($data);
	exit;
}

function get_lang(){
	if(isset($_POST['foss'])){
		$query = "select distinct tr.language from tutorial_resources tr, tutorial_details td where td.id=tr.tutorial_detail_id and td.foss_category='".$_POST['foss']."' order by tr.language";
		$result = db_query($query);
		$data = array();
		while($row = db_fetch_object($result)){
			$data[] = $row;
		}
		echo json_encode($data);
		exit;
	}
}


function get_college_details(){
	if(isset($_POST['state_code'])){
		$query = "select count(id) as ac_count from academic_center where state_code='".$_POST['state_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
		echo json_encode($row);
		exit;
	}
}

function get_academic_details(){
	global $user;
	if(isset($_POST['academic_code'])){
		$query = "select * from academic_center where academic_code='".$_POST['academic_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
		$res['academic'] = $row;
		echo json_encode($res);
		exit;
	}
}

function get_workshop_details(){
	if(isset($_POST['workshop_code'])){
		$query = "select * from workshop_requests where workshop_code='".$_POST['workshop_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
		echo json_encode($row);
		exit;
	}
}

function get_test_details(){
	if(isset($_POST['workshop_code'])){
		$query = "select * from test_requests where test_code='".$_POST['test_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
		echo json_encode($row);
		exit;
	}
}

function get_feedback_detail(){
	$row = array();
	if(isset($_POST['user_name']) && !empty($_POST['user_name'])){
		$query = "select firstname, email from {mdl_user} where username='".$_POST['user_name']."'";
		db_set_active('moodle');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
	}
	if(isset($_POST['workshop_code']) && !empty($_POST['workshop_code'])){
		$query = "SELECT academic_center.institution_name from academic_center LEFT JOIN  workshop_requests ON academic_center.academic_code = workshop_requests.academic_code WHERE workshop_requests.workshop_code ='".$_POST['workshop_code']."'";
		db_set_active('workshop_info');
		$result = db_query($query);
		db_set_active('default');
		$row = db_fetch_object($result);
	}
	echo json_encode($row);
	exit;
}


	function workshops_help($path, $arg) {
		if ($path == 'admin/help#workshop') {
			$txt = 'This module managing all the workshop detail';
			return '<p>'. t($txt) .'</p>';
		}
	}

	/**
	* Implementation of hook_block().
	*/

	function workshops_block($op = 'list', $delta = 0, $edit = array()) {
		switch ($op) {case 'list':
			$blocks[0]['info'] = t('What\'s New');
			return $blocks;
		case 'view':
			$item = get_link_item();
			if(!empty($item)) {
				$content = $item;
				$blocks['subject'] = t('Manage Workshop');
				$blocks['content'] = $content;
				return $blocks;
			}
		}
	}
			
	function get_link_item() {
		$links = '';
		$links .= '<b>'.$item->FOSS_Category.'</b><br />';
		$links .= '<ul><li><a href="'.$GLOBALS['base_path']."'".'workshops/college>College Details</a></li></ul>';

		return $links;
	}
	
	
	
	// send email
	
	function workshops_notify($mailto, $subject, $message) {
		//echo $mailfrom.$mailto.$subject.$message;
		global $custom_email;
		$mailfrom = $custom_email;
		//drupal_mail('workshops', 'reply', $mailto, language_default(), array('body' => $message, 'subject' => $subject), $mailfrom, TRUE);
	}
  
	function workshops_mail($key, &$message, $params) {
		$message['subject'] = $params['subject'];
		$message['body'] = $params['body'];
		$headers = array(
		    'MIME-Version' => '1.0',
		    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
		    'Content-Transfer-Encoding' => '8Bit',
		    'X-Mailer' => 'Drupal'
		  );
		
		foreach ($headers as $key => $value) {
		    $message['headers'][$key] = $value;
		}
	}


?>
